export const animalsData = [
  {
    id: "jackal",
    name: "Jackal",
    scientificName: "Canis aureus",
    mass: "11 – 12 kg",
    speed: "16 km/hr",
    lifespan: "8 – 10 years",
    diet: "Deer, Cows",
    type: "Omnivorous",
    gestationPeriod: "61 days",
    image: "/jackal.png",
    goal: "13k",
    raised: "5k",
    percentage: "38%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
  {
    id: "elephant",
    name: "Elephant",
    scientificName: "Loxodonta africana",
    mass: "2,700 – 6,000 kg",
    speed: "25 km/hr",
    lifespan: "60 – 70 years",
    diet: "Grass, Leaves, Fruit",
    type: "Herbivorous",
    gestationPeriod: "22 months",
    image: "/elephant.png",
    goal: "6k",
    raised: "4k",
    percentage: "82%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
  {
    id: "zebra",
    name: "Zebra",
    scientificName: "Equus quagga",
    mass: "220 – 450 kg",
    speed: "65 km/hr",
    lifespan: "20 – 25 years",
    diet: "Grasses, Shrubs",
    type: "Herbivorous",
    gestationPeriod: "12 – 13 months",
    image: "/zebra.png",
    goal: "4k",
    raised: "1k",
    percentage: "13%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
  {
    id: "tiger",
    name: "Tiger",
    scientificName: "Panthera tigris",
    mass: "90 – 300 kg",
    speed: "49 – 65 km/hr",
    lifespan: "8 – 12 years",
    diet: "Deer, Boar, Buffalo",
    type: "Carnivorous",
    gestationPeriod: "3.5 months",
    image: "/tiger.png",
    goal: "12k",
    raised: "7k",
    percentage: "56%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
  {
    id: "deer",
    name: "Deer",
    scientificName: "Odocoileus virginianus",
    mass: "45 – 150 kg",
    speed: "50 – 60 km/hr",
    lifespan: "6 – 14 years",
    diet: "Leaves, Grass, Fruits",
    type: "Herbivorous",
    gestationPeriod: "6 – 7 months",
    image: "/deer.png",
    goal: "22k",
    raised: "8k",
    percentage: "35%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
  {
    id: "bear",
    name: "Bear",
    scientificName: "Ursus arctos",
    mass: "80 – 600 kg",
    speed: "40 km/hr",
    lifespan: "20 – 30 years",
    diet: "Fish, Berries, Plants",
    type: "Omnivorous",
    gestationPeriod: "6 – 8 months",
    image: "/bear.png",
    goal: "16k",
    raised: "13k",
    percentage: "67%",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst. Vestibulum vitae felis eu neque varius venenatis eu vitae elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer consectetur mi vitae dolor. \n\n Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vitae suscipit nisl. Vivamus ullamcorper sapien leo, ac consectetur lorem convallis a. Aliquam vel nisi at diam ornare euismod interdum ornare nibh. In hac habitasse platea dictumst.",
  },
];

export const tickets = [
  {
    name: "Family (2 Adults & 2 Children or 1 Adult & 3 Children)",
    price: 50,
  },
  { name: "Adult (16–59 years)", price: 15.95 },
  {
    name: "Children (2–15 years)",
    price: 12.95,
    note: "Children under 16 must be accompanied by an adult.",
  },
  { name: "Under 2's", price: 0 },
  { name: "Seniors (60+ years)", price: 14.95 },
  { name: "Chelsea Pensioners", price: 0 },
  {
    name: "Student & Military Concessions",
    price: 14.95,
    note: "ID required",
  },
  { name: "Registered Disabled Adult", price: 14.95, note: "1 carer free" },
  { name: "Registered Disabled Child", price: 11.95, note: "1 carer free" },
];
